### ISSUE TITLE
5.1-ready?

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [elan-ev/CliqrPlugin#137]
In unserer Stud.IP 5.1 funktioniert die aktuelle Version (3.2.0) leider nicht. Öffne ich Cliqr in einer Veranstaltung ist der Inhalt weiß, alle Links in der Subnavigation werden im neuen Tab geöffnet und auch hier weißer Inhalt.

Folgender Fehler taucht im Browser in der Console auf:

```
Uncaught 
constructor
message: "An \"el\" must exist in DOM for this region mnr12"
name: "RegionError"
url: "http://marionettejs.com/docs/v4.1.3/marionette.region.html#additional-options"
stack: "RegionError: An \"el\" must exist in DOM for this region mnr12\n    at ct._ensureElement (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:41435)\n    at ct.show (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:39380)\n    at r.showChildView (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:45858)\n    at r.initialize (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:271270)\n    at r.e.View (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:16186)\n    at r.constructor (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:46462)\n    at new r (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:24161)\n    at r.initialize (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:272810)\n    at r.e.View (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:16186)\n    at r.constructor (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:46462)\n    at new r (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:24161)\n    at r.onStart (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:273625)\n    at r.D [as triggerMethod] (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:27939)\n    at r.start (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:61054)\n    at z.<anonymous> (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:273835)\n    at z.i (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:149047)\n    at z.context (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:148681)\n    at Module.<anonymous> (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:273806)\n    at i (https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:361)\n    at https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:2314\n    at https://tokio.elsa.uni-hannover.de/plugins_packages/elan-ev/CliqrPlugin/dist/studip-cliqr.js?v=3.2.0:1:2325"
[[Prototype]]: Error
```

![image](https://user-images.githubusercontent.com/53210931/154948291-02cd1246-3aec-4be8-88c2-45f5bb29088a.png)

**Comment by schuettloeffel-elsa** [comment]
Hi, wir haben diesen Fix jetzt drin:
https://gitlab.studip.de/studip/studip/-/issues/697

Leider kommt nun ein neuer Fehler:

```
Nachricht: Call to undefined function studip_utf8encode()
Code: 0
Stack trace:
#$ public/plugins_packages/elan-ev/CliqrPlugin/app/views/app/index.php(6)
#0 vendor/flexi/lib/php_template.php(46): require()
#1 vendor/flexi/lib/template.php(157): Flexi_PhpTemplate->_render()
#2 vendor/trails/trails.php(764): Flexi_Template->render()
#3 vendor/trails/trails.php(724): Trails_Controller->render_template('app/index', NULL)
#4 vendor/trails/trails.php(564): Trails_Controller->render_action('index')
#5 app/controllers/studip_controller.php(110): Trails_Controller->perform('')
#6 vendor/trails/trails.php(154): StudipController->perform('')
#7 vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('')
#8 public/plugins_packages/elan-ev/CliqrPlugin/CliqrPlugin.php(98): Trails_Dispatcher->dispatch('')
#9 public/plugins.php(54): CliqrPlugin->perform('')
#10 {main}
```

**Comment by schuettloeffel-elsa** [comment]
hat sich erledigt, habs ausversehen mit der alten Version getestet, läuft nun.
